"""Emit the runtime hose profile from reviewed rig and SDK bind measurements.

This only prints source (or checks an existing file); it never edits artist art,
compiles the SDK, or copies lab code into the runtime. Use apply_patch to accept
the generated Lua, then verify it against the final production bundle.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RIG_CONTRACT = ROOT / "tools/hose_lab/rig/runtime_contract.json"
PROFILE = ROOT / "scripts/mods/doomrocket/utils/doomrocket_hose_profile.lua"


def vector(values):
    return "{ " + ", ".join(format(value, ".17g") for value in values) + " }"


def frame(matrix, indent="\t\t\t"):
    result = []
    for column, name in enumerate(("x_axis", "y_axis", "z_axis", "position")):
        result.append(f"{indent}{name} = {vector([matrix[row][column] for row in range(3)])},")
    return "\n".join(result)


def generate(contract, report):
    if report["actors"] != 0 or report["deforming_controls"] != 29:
        raise ValueError("A hose profile requires an independently verified actor-free 29-control rig")
    if [entry["name"] for entry in contract["controls"]] != [entry["name"] for entry in report["controls"]]:
        raise ValueError("Compiled and authored control orders differ")
    lines = [
        "-- Generated by tools/build_hose_profile.py from the reviewed rig + SDK bind audit.",
        "-- Columns are Stingray x/y/z basis and translation; preserve every scale.",
        "-- Desired world bone = control world * bind (column-vector notation).",
        "-- Endpoint frames are local to the named live nodes, not posed-hand inverses.",
        "-- The lower grip inlet is inferred from geometry and awaits artist acceptance.",
        "return {",
        '\tschema = 1,',
        '\tunit = "units/warlock_hose/warlock_hose",',
        '\tparent_node = "hose_root",',
        '\tmaterial_slot = "DoomRocket_Weapon",',
        '\tmaterial_child = "child_materials/warlock_bombardier/wb_hose_child",',
        '\ttextures = { "textures/rocket/wb_weapon_df", "textures/rocket/wb_weapon_nm", "textures/rocket/wb_weapon_ma" },',
        f'\tfbx_sha256 = "{contract["outputs"]["fbx_sha256"]}",',
        f'\tlengths = {vector(contract["control_rest_lengths_m"])},',
        "\tendpoints = {",
    ]
    for name in ("pack", "weapon"):
        endpoint = contract["endpoints"][name]
        lines.extend((f"\t\t{name} = {{", f'\t\t\tnode = "{endpoint["target_node"]}",',
                      frame(endpoint["target_local_frame"]), "\t\t},"))
    lines.extend(("\t},", "\tcontrols = {"))
    for authored, compiled in zip(contract["controls"], report["controls"]):
        lines.extend(("\t\t{", f'\t\t\tname = "{authored["name"]}",', "\t\t\trest = {",
                      frame(authored["frame"], "\t\t\t\t"), "\t\t\t},", "\t\t\tbind = {",
                      frame(compiled["control_to_compiled_bone"], "\t\t\t\t"), "\t\t\t},", "\t\t},"))
    lines.extend(("\t},", "}", ""))
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--contract", type=Path, default=RIG_CONTRACT)
    parser.add_argument("--check", type=Path, nargs="?", const=PROFILE)
    args = parser.parse_args()
    generated = generate(json.loads(args.contract.read_text(encoding="utf-8")),
                         json.loads(args.report.read_text(encoding="utf-8")))
    if args.check:
        if args.check.read_text(encoding="utf-8") != generated:
            raise SystemExit("Runtime hose profile differs from the measured rig/compiled binds")
        print("Runtime hose profile exactly matches reviewed measurements")
    else:
        print(generated, end="")


if __name__ == "__main__":
    main()
